### PR TITLE
fix: :bug: fixed issue with expanding of errors and screenshots

### LINKED ISSUE #421: Screenshots and Errors not expanding after v3.9.1
# Environment (please complete the following information)

- multiple-cucumber-html-reporter: 3.9.0

## Describe the bug

The DataTable on the report landing page isn't working - the following error is shown in the console:

> Uncaught TypeError: $(...).dataTable is not a function

It looks like commit bd58e2ce7729d39dd01a56e65911173faee2dbb7 went a little wobbly. For example the contents of jquery.dataTables.min.js was replaced, not with an update to DataTables core, but rather with the jQuery UI integration for DataTables, which I doubt is what you want since you have Bootstrap loaded on the page. Additionally, the `dataTables.bootstrap.min.js` file contains CSS.

## To Reproduce

Install multiple-cucumber-html-reporter@3.9.0 and create a report. The main table on the index page will not be a DataTable.

## Expected behavior

A DataTable should be created, like in the readme screenshots.

## Additional context

Disclosure, I'm the author for DataTables and a friend let me know they were having problems after updating to 3.9.0.

### PR DESCRIPTION
**Pull request by WasiqB**
# Fixes #421

### CODE REVIEW

**Comment by WasiqB** [comment]
:rocket: _This pull request is included in v3.9.2. See [Release 3.9.2](https://github.com/WasiqB/multiple-cucumber-html-reporter/releases/tag/v3.9.2) for release notes._
