### ISSUE TITLE
Screenshots and Errors not expanding after v3.9.1

### ISSUE THREAD

**Issue by AllanJard** [WasiqB/multiple-cucumber-html-reporter#421]
# Environment (please complete the following information)

- multiple-cucumber-html-reporter: 3.9.0

## Describe the bug

The DataTable on the report landing page isn't working - the following error is shown in the console:

> Uncaught TypeError: $(...).dataTable is not a function

It looks like commit bd58e2ce7729d39dd01a56e65911173faee2dbb7 went a little wobbly. For example the contents of jquery.dataTables.min.js was replaced, not with an update to DataTables core, but rather with the jQuery UI integration for DataTables, which I doubt is what you want since you have Bootstrap loaded on the page. Additionally, the `dataTables.bootstrap.min.js` file contains CSS.

## To Reproduce

Install multiple-cucumber-html-reporter@3.9.0 and create a report. The main table on the index page will not be a DataTable.

## Expected behavior

A DataTable should be created, like in the readme screenshots.

## Additional context

Disclosure, I'm the author for DataTables and a friend let me know they were having problems after updating to 3.9.0.

**Comment by AllanJard** [comment]
I was going to send a PR for this, but I don't actually know if you are using Bootstrap 3 or Bootstrap 5. If `useCDN` is true, then Bootstrap 3 is loaded. But the local `bootstrap.min.css` appears to contain Bootstrap 5. Should they be insync, or is that intentional?

**Comment by WasiqB** [comment]
@AllanJard , can you check with the latest version 3.9.1? This issue should be fixed now.

**Comment by colin0117** [comment]
I tried, ll 3.9.1, it's definitely better, not getting load errors. Screenshots and errors are no longer being displayed though for individual tests, so ongoing issues still I'm afraid. I'll revert to 3.1.0, everything is happy with that one.
